# Generated by Django 3.2.7 on 2021-10-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20211001_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='uuid',
            new_name='id',
        ),
    ]
